INSERT INTO `TB_USER`(USER_CD, USER_ID, USER_PW, INSERT_DT, DELETE_YN) VALUES ('1', 'test', '{bcrypt}$2a$10$0R/q12.ejv1oXyDAQxKXd.ai/JD3GUYFi0F8xAXS.Yy2c8ncuhwWi', now(), 'N');
INSERT INTO `TB_AUTH`(AUTH_CD, AUTH_TYPE, USER_CD) VALUES ('1', 'USER', '1');
INSERT INTO `TB_USER`(USER_CD, USER_ID, USER_PW, INSERT_DT, DELETE_YN) VALUES ('2', 'test_mart', '{bcrypt}$2a$10$0R/q12.ejv1oXyDAQxKXd.ai/JD3GUYFi0F8xAXS.Yy2c8ncuhwWi', now(), 'N');
INSERT INTO `TB_AUTH`(AUTH_CD, AUTH_TYPE, USER_CD) VALUES ('2', 'MART', '2');

INSERT INTO `TB_GOODS`(GOODS_CD, GOODS_NM, INSERT_DT, DELETE_YN) VALUES ('1', 'test_goods1', now(), 'N');
INSERT INTO `TB_GOODS_PRICE`(GOODS_PRICE_CD, GOODS_CD, GOODS_PRICE, INSERT_DT, DELETE_YN) VALUES ('1', '1', '10000', now(), 'N');
INSERT INTO `TB_GOODS`(GOODS_CD, GOODS_NM, INSERT_DT, DELETE_YN) VALUES ('2', 'test_goods2', now(), 'N');
INSERT INTO `TB_GOODS_PRICE`(GOODS_PRICE_CD, GOODS_CD, GOODS_PRICE, INSERT_DT, DELETE_YN) VALUES ('2', '2', '15000', now(), 'N');
INSERT INTO `TB_GOODS_PRICE`(GOODS_PRICE_CD, GOODS_CD, GOODS_PRICE, INSERT_DT, DELETE_YN) VALUES ('3', '1', '8000', now(), 'N');
