INSERT INTO `TB_USER`(USER_CD, USER_ID, USER_PW, INSERT_DT, DELETE_YN) VALUES ('1', 'test', '{bcrypt}$2a$10$0R/q12.ejv1oXyDAQxKXd.ai/JD3GUYFi0F8xAXS.Yy2c8ncuhwWi', now(), 'N');
INSERT INTO `TB_AUTH`(AUTH_CD, AUTH_TYPE, USER_CD) VALUES ('1', 'USER', '1');
INSERT INTO `TB_USER`(USER_CD, USER_ID, USER_PW, INSERT_DT, DELETE_YN) VALUES ('2', 'test_mart', '{bcrypt}$2a$10$0R/q12.ejv1oXyDAQxKXd.ai/JD3GUYFi0F8xAXS.Yy2c8ncuhwWi', now(), 'N');
INSERT INTO `TB_AUTH`(AUTH_CD, AUTH_TYPE, USER_CD) VALUES ('2', 'MART', '2');

INSERT INTO `TB_GOODS`(GOODS_CD, GOODS_NM, INSERT_DT, DELETE_YN) VALUES ('1', 'test_goods1', now(), 'N');
INSERT INTO `TB_GOODS_PRICE`(GOODS_PRICE_CD, GOODS_CD, GOODS_PRICE, INSERT_DT, CURRENT_PRICE_YN, DELETE_YN) VALUES ('1', '1', '10000', '2023-09-07 11:00:00', 'Y', 'N');
INSERT INTO `TB_GOODS`(GOODS_CD, GOODS_NM, INSERT_DT, DELETE_YN) VALUES ('2', 'test_goods2', now(), 'N');
INSERT INTO `TB_GOODS_PRICE`(GOODS_PRICE_CD, GOODS_CD, GOODS_PRICE, INSERT_DT, CURRENT_PRICE_YN, DELETE_YN) VALUES ('2', '2', '15000', '2023-09-07 08:00:00', 'Y', 'N');
INSERT INTO `TB_GOODS_PRICE`(GOODS_PRICE_CD, GOODS_CD, GOODS_PRICE, INSERT_DT, CURRENT_PRICE_YN, DELETE_YN) VALUES ('3', '1', '8000', '2023-09-07 15:00:00', 'N', 'N');

INSERT INTO `TB_COUPON`(COUPON_CD, GOODS_CD, COUPON_NM, COUPON_TYPE, DISCOUNT, INSERT_DT, DELETE_YN) VALUES ('1', '1', 'coupon(test_goods1, 20%)', 'RATE', 20, now(), 'N');
INSERT INTO `TB_COUPON`(COUPON_CD, GOODS_CD, COUPON_NM, COUPON_TYPE, DISCOUNT, INSERT_DT, DELETE_YN) VALUES ('2', '1', 'coupon(test_goods1, 5000)', 'FIX', 5000, now(), 'N');
INSERT INTO `TB_COUPON`(COUPON_CD, GOODS_CD, COUPON_NM, COUPON_TYPE, DISCOUNT, INSERT_DT, DELETE_YN) VALUES ('3', '2', 'coupon(test_goods2, 13%)', 'RATE', 13, now(), 'N');
INSERT INTO `TB_COUPON`(COUPON_CD, GOODS_CD, COUPON_NM, COUPON_TYPE, DISCOUNT, INSERT_DT, DELETE_YN) VALUES ('4', '2', 'coupon(test_goods2, 1327)', 'FIX', 1327, now(), 'N');
INSERT INTO `TB_COUPON`(COUPON_CD, COUPON_NM, COUPON_TYPE, DISCOUNT, INSERT_DT, DELETE_YN) VALUES ('5', 'coupon(total, 24%)', 'RATE', 24, now(), 'N');
INSERT INTO `TB_COUPON`(COUPON_CD, COUPON_NM, COUPON_TYPE, DISCOUNT, INSERT_DT, DELETE_YN) VALUES ('6', 'coupon(total, 6937)', 'FIX', 6937, now(), 'N');
